DefaultContentLanguage = "es"
MetaDataFormat = "yaml"
baseURL = "https://example.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
relativeURLs = true
theme = "gohugo-theme-ananke"
title = "Asociación de Capacitación e Investigación para la salud mental"
[params]
description = "The last theme you'll ever need. Maybe."
facebook = "https://www.facebook.com/acisam/"
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 4
site_logo = "images/Acisam.jpg"
twitter = ""
youtube = "https://www.youtube.com/user/evmacisam"
[permalinks]
novedades = "/:sections/:title/"
proyectos = "/:sections/:title/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
mainSections = "novedades"
priority = 0.5
