DefaultContentLanguage = "es"
MetaDataFormat = "yaml"
baseURL = "https://www.acisam.netlify.com"
enableRobotsTXT = true
languageCode = "es-sv"
relativeURLs = true
title = "Asociación de Capacitación e Investigación para la salud mental"
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
facebook = "https://www.facebook.com/acisam/"
favicon = "favicon.ico"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 2
site_logo = "staticimg/logo.jpg"
twitter = ""
youtube = "https://www.youtube.com/user/evmacisam"
[permalinks]
editorial = "/:sections/:title/"
ejes-de-trabajo = "/:sections/:title/"
multimedia = "/:sections/:title/"
novedades = "/:sections/:title/"
proyectos = "/:sections/:title/"
quienes-somos = "/:sections/:title/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
mainSections = "novedades"
priority = 0.5
[blackfriday]
    extensions = ["hardLineBreak"]