backend:
  name: git-gateway
  branch: master 
media_folder: "content/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
display_url: https://acisam.netlify.com/index.html
collections:
  - label: "Instrucciones"
    name: "instrucciones"
    files:
      - label: "Lea me primero!!"
        name: "lea-me"
        file: "static/admin/readme.md"
        fields:
          - {label: "Titulo", name: "title", widget: "string"}
          - {label: "Descripcion", name: "despcription", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "novedades" # Used in routes, e.g., /admin/collections/blog
    label: "Novedades" # Used in the UI
    folder: "content/novedades" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "post"}
      - {label: "Imagen grande", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "quienes-somos" # Used in routes, e.g., /admin/collections/blog
    label: "Quienes Somos" # Used in the UI
    folder: "content/quienes-somos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "page"}
      - label: "Menu"
        name: "menu"
        widget: "object"
        fields: 
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - {label: "Contiendo en Menu", name: "parent", widget: "string"}
              - {label: "Orden", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "proyectos" # Used in routes, e.g., /admin/collections/blog
    label: "Proyectos" # Used in the UI
    folder: "content/proyectos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "page"}
      - label: "Menu"
        name: "menu"
        widget: "object"
        fields: 
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - {label: "Contiendo en Menu", name: "parent", widget: "string"}
              - {label: "Orden", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "multimedia" # Used in routes, e.g., /admin/collections/blog
    label: "Multimedia" # Used in the UI
    folder: "content/multimedia" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "page"}
      - label: "Menu"
        name: "menu"
        widget: "object"
        fields: 
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - {label: "Contiendo en Menu", name: "parent", widget: "string"}
              - {label: "Orden", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "ejes-de-trabajo" # Used in routes, e.g., /admin/collections/blog
    label: "Ejes de Trabajo" # Used in the UI
    folder: "content/ejes-de-trabajo" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "page"}
      - label: "Menu"
        name: "menu"
        widget: "object"
        fields: 
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - {label: "Contiendo en Menu", name: "parent", widget: "string"}
              - {label: "Orden", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "editorial" # Used in routes, e.g., /admin/collections/blog
    label: "Editorial" # Used in the UI
    folder: "content/editorial" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "page"}
      - label: "Menu"
        name: "menu"
        widget: "object"
        fields: 
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - {label: "Contiendo en Menu", name: "parent", widget: "string"}
              - {label: "Orden", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}