backend:
  name: git-gateway
  branch: master 
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "novedades" # Used in routes, e.g., /admin/collections/blog
    label: "Novedades" # Used in the UI
    folder: "content/novedades" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string", default: "{{slug}}"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Descripcion", name: "description", widget: "string", default: "{{slug}}"}
      - {label: "Tipo", name: "type", widget: "hidden", default: "post"}
      - {label: "Imagen grande", name: "featured_image", widget: "image"}
