---
upload_path: "/static/img/post/:year:/:month:/:day:"
frontmatter_file_url_template: "/img/post/:year:/:month:/:day:"
body_file_url_template: "/post/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections: 
version: 0.31.1
